### ISSUE TITLE
Set DNS server and outbound proxy server from application layer

### ISSUE THREAD

**Issue by morosev** [runamedia/rtcsip#10]

**Comment by gstream** [comment]
Hello
Hope to hearing your answer about this issue asap.
Thanks

**Comment by morosev** [comment]
@gstream Proxy server is fixed. It can be set from application. DNS is also controllable from there.
iOS - rtcsip/samples/ios/DemoApp/Consts.h - set defines
Android - rtcsip/samples/android/DemoApp/app/src/main/java/com/runamedia/rtc/demoapp/MainActivity.java - set static final strings
