### ISSUE TITLE
Upgrade Android build system to NDK r11

### ISSUE THREAD

**Issue by morosev** [runamedia/rtcsip#11]
There is a linking error when system is built for NDK r11.

**Comment by jockyxiao** [comment]
There still is a linking error when system is built for NDK r11. what should i do? thanks!

**Comment by morosev** [comment]
@jockyxiao: Thank you for you interest into this library.
I'm sorry, but NDK r11 is not fixed yet and this issue is still open. The support for NDK r11 will be done along with update of WebRTC and reSIProcate prebuilt binaries to new versions (the current version is from December 2015).
You can use NDK r10 for now and there will be no difference. This NDK can be downloaded from here: http://dl.google.com/android/repository/android-ndk-r10e-darwin-x86_64.zip
Looks like the NDK ABI compatibility between r10 and r11 has been broken.
