### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by gstream** [runamedia/rtcsip#12]
Android Demo is crashed when connect. (not tested iOS demo)

**Comment by morosev** [comment]
I have just finished Android testing and haven't noticed a problem. But I don't use outbound proxy server in my test scenario. I will check this.

**Comment by morosev** [comment]
One note - you have to run rtcsip_build_android.sh script again, because native code for Android platform has been changed in fix #10.

**Comment by gstream** [comment]
I've rebuilt jni with rtcsip_build_android.sh.

But I got  crashed when connect.
On my case, I m using outbound proxy server.

**Comment by gstream** [comment]
I've tested android demo without outbound proxy.
when using outbound proxy, this demo get crashes.

**Comment by morosev** [comment]
This problem is related to issue #10.

**Comment by morosev** [comment]
@gstream The problem is fixed. You can try it now again.

**Comment by gstream** [comment]
Hi morosev
This issue is not  fixed.
When app try to reconnect, app get crashes.

**Comment by morosev** [comment]
Created issue #15 for this bug.
