### ISSUE TITLE
How to know callback result?

### ISSUE THREAD

**Issue by gstream** [runamedia/rtcsip#14]
Hello morosev

As you know, I m using your demo for android client of my sip server.

Would you like to let me know how can I know the login/call result callback ?

I need to know that user login is failed or successed.

**Comment by morosev** [comment]
Hi @gstream.
You can find samples how to listen for events from rtcsip engine in samples/android/DemoApp/app/src/main/java/com/runamedia/rtc/demoapp/MainActivity.java, methods sipController.registerOnRegistrationEventListener(), sipController.registerOnCallEventListener() and sipController.registerOnErrorEventListener().

**Comment by gstream** [comment]
Ah, Thanks
