### ISSUE TITLE
Can't make call between different codec.

### ISSUE THREAD

**Issue by gstream** [runamedia/rtcsip#16]
Hi @morosev 

could you let me know current codec of your demo ?( for video & audio)

When I make call with your demo, I can't hear anything between different codec.
Is there any solution ?

**Comment by morosev** [comment]
Hi @gstream,

When a call is initialized from rtcsip engine, the highest priority codecs are Opus for audio and VP8 for video and they will be used during the call.

When rtcsip engine talks to FreeSwitch service (automatic message that is played when user is  not available) it can be seen from SDP sent from FreeSwitch server that Opus is the highest priority codec, so it is used in this case.

WebRTC supports also G711, G722, iSAC, iLBC audio and VP9 video codecs, but looks like they wouldn't be used in any call scenario between rtcsip apps over FreeSwtch.

**Comment by gstream** [comment]
Hi @morosev 
When I make call with your demo, I can't hear anything between different codec.
Is there any solution ?

**Comment by morosev** [comment]
@gstream I don't understand exactly the case that you are talking about. Can you provide more details about it. Different codecs cannot talk between each other. But WebRTC contains standard set of codecs and it can choose the right one needed for communication.

**Comment by gstream** [comment]
Hi @morosev 
Sorry my poor information.

When I use your demo, need to add some configuration parts you teached  to freeswitch configuration?

I m using kazoo for freeswitch.

By default, "inbound-bypass-media" is commented.
Also there is no "global_codec_prefs" and "outbound_codec" options for standard.

Must add these options to freeswitch configuration?

**Comment by gstream** [comment]
@morosev  I can make audio call with your demo. But quality is very bad.

Is there any solution?
