### ISSUE TITLE
How to know type of incoming call ?

### ISSUE THREAD

**Issue by gstream** [runamedia/rtcsip#18]
Current SDK designed for only video call.

Is there any solution to know type of incoming call (video call, audio call ) ?

**Comment by gstream** [comment]
This sdk is still available ?

**Comment by morosev** [comment]
@gstream Sorry for not responding for a long time. I have a lot of higher priority issues on other projects, so wasn't active here for a while.
The type of incoming call cannot be detected at a moment. I filed a new issue for this feature: #19
You can chose on the client side whether initiating call will be audio only or audio/video. There is an issue related to audio only call on iOS: #9
