### ISSUE TITLE
Send a type of incoming call (audio or audio/video) to the user layer

### ISSUE THREAD

**Issue by morosev** [runamedia/rtcsip#19]

**Comment by gstream** [comment]
Hello @morosev 
Is there any update with this issue ?

**Comment by gstream** [comment]
Hey @morosev 
Let me know your availability This repo cant get any support from you now?

**Comment by gstream** [comment]
Hi @morosev 
Would you like to solve this issue ? 
I m using this library for video/audio call on my app. But I cant build app because I cant detect incoming call type (video call or audio call).

Hope to get solution from you soon.
Thanks

**Comment by morosev** [comment]
@gstream The support to this repo is very limited at a moment. Some blocking issues, such as #15, will be fixed, but all others related to enhancement of current features won't be fixed soon. There is some development in progress of new iOS test client that will be implemented in Swift.
Production quality status for this project should not be expected before the end of the summer.

**Comment by morosev** [comment]
@gstream I will take a look over this issue as well.

**Comment by gstream** [comment]
Hi @morosev 
When could you update this issue?
