### ISSUE TITLE
Poor quality of audio transmission.

### ISSUE THREAD

**Issue by gstream** [runamedia/rtcsip#20]
When 2 clients make call each other (iOS), audio is very poor (sometimes nothing to hear) as well as video also.

Is there any solution to improve this issue ?

**Comment by morosev** [comment]
This should be checked further. Poor media quality can be produced from many reasons, including networking issues.

**Comment by gstream** [comment]
Hi @morosev 
Thanks for your reply.
This issue happens only on iOS. Android version is working well.
