### ISSUE TITLE
Android Demo is not working on 4.4 or lower

### ISSUE THREAD

**Issue by gstream** [runamedia/rtcsip#21]
When I tested demo with android 5.1 and 5.1, it worked well.

But when I tested demo on android 4.4 or lower, It doesnt worked.

**Comment by gstream** [comment]
Hi @morosev 
is there any update ?

may i wait your response ?

**Comment by morosev** [comment]
@gstream Versions lower than 5 for Android are not supported yet. I will mark this issue as a bug.
