### ISSUE TITLE
Add instructions for setting up FreeSWITCH and TURN servers

### ISSUE THREAD

**Issue by morosev** [runamedia/rtcsip#5]

**Comment by gstream** [comment]
Hello Morosev
Thanks for your great Demo.

I want to integrate your demo with my sip server. (kamilio/freeswitch).

Is there any good reference for this ?

Hope to hearing from you soon.
Thanks

**Comment by gstream** [comment]
Hello morosev
I m gong to integrate your demo with my kamilio/freeswitch.
Then how can I set outbound proxy with your demo?

**Comment by morosev** [comment]
Hi gstream. Thank you for being interested in this library. The instructions for Freeswitch will be added to README today. There haven't been much activity on this repository recently, but the present tasks will be swept out soon.
Thanks.

**Comment by morosev** [comment]
To change target SIP server:
- Android - samples/android/DemoApp/app/src/main/java/com/runamedia/rtc/demoapp/MainActivity.java, line 66, change the final string value;
- iOS - samples/ios/DemoApp/Consts.h, line 44, change server domain.

**Comment by gstream** [comment]
Hi morosev
Thanks for your reply.
I changed target SIP server. (MainActivity.java, line 66).

I m new to here so my question is maybe silly.

What I want to know is how can I set realm with your demo.
I tested my kamilio/freeswitch with zoiper.

I've attached it.

I changed domain name with your demo. (outbound proxy).

Then I can I set domain (realm) with your demo ?

Hope to hearing from you soon.
Thanks
![zoiper](https://cloud.githubusercontent.com/assets/17048847/14430017/8e0a22f0-0008-11e6-9f38-d51fe728f3c5.png)

**Comment by gstream** [comment]
My sip server is sip.vozy.co.
realm is testappandroid.vozy.co.

How can I set testappandroid.vozy.co (realm) with your demo?

**Comment by gstream** [comment]
Hi  morosev
This is urgent project for me with your demo.
How can I set realm with your demo?

Hope to hearing from you soon.
Regards

**Comment by morosev** [comment]
OK. Going to see whether realm can be set to resiprocate engine and if it can be done I will expose the method to the API.

**Comment by morosev** [comment]
Realm is set automatically in Authentication Module to domain name. The API will be extended to support setting up the outbound proxy -> #10

**Comment by gstream** [comment]
Hello
I need to set realm as difference with domain name.
On my state, domain name is sip.vozy.co and realm is testappandroid.vozy.co.
Please update me asap.
Thanks

**Comment by morosev** [comment]
I checked few SIP softphones and I cannot see "realm" setting in account settings. Even, realm doesn't exist as a setting in resiprocate API.
How do you set "realm" value in zoiper application?
@gstream

**Comment by gstream** [comment]
I attached my zoiper account setting screenshot on above question.

There is "Domain" and "Outbound proxy" options in account preference.

On your demo, only can set Domain (I don't know it's outbound proxy).

I need to set Domain and outbound proxy as above attached screenshot with your demo.

Any other solution?

**Comment by morosev** [comment]
Yes, the outbound proxy is fixed in issue #10. You can merge the changes and try to set the outbound proxy parameter. You will be able to set all the parameters like it is done in zoiper.

Also, the instructions for setting up FreeSwitch and Turn are supplied in README.md. Closing this issue.

**Comment by gstream** [comment]
Hi morosev

Did you check demo after your's last commit?

Current demo is crashed when connect.
