### ISSUE TITLE
Fix failure on audio only call on iOS

### ISSUE THREAD

**Issue by morosev** [runamedia/rtcsip#9]

**Comment by gstream** [comment]
is there any solution to fix this issue ?

**Comment by gstream** [comment]
@morosev , What do you think about this issue ?

Do you have any solution to fix this issue ? Please respond me.
Thanks

**Comment by gstream** [comment]
I've checked audio call on android sdk. it works well.

**Comment by morosev** [comment]
@gstream - this one is fixed.
